import test from "node:test";
import assert from "node:assert/strict";
import { createServer, request } from "node:https";
import { execFileSync } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { X509Certificate, createPublicKey } from "node:crypto";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { readRemoteIcon } from "../src/engine/catalog-icon";

test("Real controlled HTTPS icon transport: verified TLS, pinned lookup, redirects, no credentials, bounded body and cancellation", async () => {
  const dir = await mkdtemp(join(tmpdir(), "synora-icon-tls-"));
  const supplied = process.env.SYNORA_QA_ICON_TLS_DIR;
  if (supplied) {
    // QA-only portable certificate input, generated by our own test runner.
    // TLS verification below remains enabled; never import trust into the OS.
    const certificate = await readFile(join(supplied, "cert.pem"));
    const key = await readFile(join(supplied, "key.pem"));
    const x509 = new X509Certificate(certificate);
    assert.equal(x509.checkHost("icons.test"), "icons.test");
    assert.ok(Date.parse(x509.validFrom) <= Date.now());
    assert.ok(Date.parse(x509.validTo) > Date.now());
    assert.deepEqual(
      x509.publicKey.export({ type: "spki", format: "der" }),
      createPublicKey(key).export({ type: "spki", format: "der" }),
    );
    await writeFile(join(dir, "cert.pem"), certificate, {
      flag: "wx",
      mode: 0o600,
    });
    await writeFile(join(dir, "key.pem"), key, { flag: "wx", mode: 0o600 });
  } else
    execFileSync(
      "openssl",
      [
        "req",
        "-x509",
        "-newkey",
        "ec",
        "-pkeyopt",
        "ec_paramgen_curve:P-256",
        "-nodes",
        "-keyout",
        join(dir, "key.pem"),
        "-out",
        join(dir, "cert.pem"),
        "-days",
        "1",
        "-subj",
        "/CN=icons.test",
        "-addext",
        "subjectAltName=DNS:icons.test",
      ],
      { stdio: "ignore" },
    );
  const cert = await readFile(join(dir, "cert.pem"));
  const seen: { path: string; headers: Record<string, unknown> }[] = [];
  const sockets = new Set<import("node:tls").TLSSocket>();
  const body = Buffer.from(
    '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><circle r="10" cx="16" cy="16"/></svg>',
  );
  const server = createServer(
    { key: await readFile(join(dir, "key.pem")), cert },
    (req, res) => {
      seen.push({ path: req.url!, headers: req.headers });
      if (req.url === "/redirect") {
        res.writeHead(302, { Location: "/original" });
        res.end();
      } else if (req.url === "/private") {
        res.writeHead(302, { Location: "https://127.0.0.1/private" });
        res.end();
      } else if (req.url === "/loop") {
        res.writeHead(307, { Location: "/loop" });
        res.end();
      } else if (req.url === "/large") {
        res.writeHead(200, { "Content-Length": 600000 });
        res.end();
      } else if (req.url === "/chunked") {
        res.writeHead(200);
        res.end(Buffer.alloc(600000));
      } else if (req.url === "/gzip") {
        res.writeHead(200, { "Content-Encoding": "gzip" });
        res.end(body);
      } else if (req.url === "/missing") {
        res.writeHead(404);
        res.end("not an image");
      } else if (req.url === "/hold") {
        res.writeHead(200);
        res.write(body.subarray(0, 15));
      } else res.end(body);
    },
  );
  server.on("secureConnection", (socket) => {
    sockets.add(socket);
    socket.once("close", () => sockets.delete(socket));
  });
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const port = (server.address() as import("node:net").AddressInfo).port;
  let lookups = 0;
  // Host-only test transport maps the approved public address to the isolated
  // TLS fixture. Neither this option nor a trust override is exposed over IPC.
  const network = {
    lookup: async () => {
      lookups++;
      return [{ address: "8.8.8.8", family: 4 }];
    },
    request: ((url: URL, options: any, callback: any) => {
      assert.equal(options.rejectUnauthorized, true);
      assert.equal(options.agent, false);
      options.lookup(
        "icons.test",
        { all: true },
        (e: unknown, addresses: unknown) => {
          assert.equal(e, null);
          assert.deepEqual(addresses, [{ address: "8.8.8.8", family: 4 }]);
        },
      );
      options.lookup(
        "icons.test",
        {},
        (e: unknown, address: string, family: number) => {
          assert.equal(e, null);
          assert.equal(address, "8.8.8.8");
          assert.equal(family, 4);
        },
      );
      return request(
        url,
        {
          ...options,
          port,
          ca: cert,
          lookup: (_host: unknown, opts: any, cb: Function) => {
            if (opts.all) cb(null, [{ address: "127.0.0.1", family: 4 }]);
            else cb(null, "127.0.0.1", 4);
          },
        },
        callback,
      );
    }) as typeof request,
  };
  try {
    assert.deepEqual(
      await readRemoteIcon(
        "https://icons.test/redirect",
        AbortSignal.timeout(2000),
        network,
      ),
      body,
    );
    assert.deepEqual(
      seen.map((r) => r.path),
      ["/redirect", "/original"],
    );
    assert.equal(lookups, 2);
    for (const record of seen)
      for (const h of [
        "authorization",
        "cookie",
        "referer",
        "proxy-authorization",
      ])
        assert.equal(record.headers[h], undefined);
    for (const path of [
      "private",
      "loop",
      "large",
      "chunked",
      "gzip",
      "missing",
    ]) {
      await assert.rejects(
        readRemoteIcon(
          `https://icons.test/${path}`,
          AbortSignal.timeout(2000),
          network,
        ),
      );
    }
    assert.equal(
      seen.some((r) => r.path === "/private/private"),
      false,
    );
    const c = new AbortController();
    const held = readRemoteIcon("https://icons.test/hold", c.signal, network);
    for (let i = 0; i < 100 && !seen.some((r) => r.path === "/hold"); i++)
      await new Promise((r) => setTimeout(r, 5));
    assert.ok(seen.some((r) => r.path === "/hold"));
    c.abort();
    await assert.rejects(held);
    for (let i = 0; i < 100 && sockets.size; i++)
      await new Promise((r) => setTimeout(r, 5));
    assert.equal(sockets.size, 0);
    const before = seen.length;
    const privateDns = {
      ...network,
      lookup: async () => [{ address: "127.0.0.1", family: 4 }],
    };
    await assert.rejects(
      readRemoteIcon(
        "https://icons.test/original",
        AbortSignal.timeout(2000),
        privateDns,
      ),
      /public addresses/,
    );
    assert.equal(seen.length, before);
    const slowDns = {
      ...network,
      lookup: () => new Promise<import("node:dns").LookupAddress[]>(() => {}),
    };
    await assert.rejects(
      readRemoteIcon(
        "https://icons.test/original",
        AbortSignal.timeout(30),
        slowDns,
      ),
    );
    assert.equal(seen.length, before);
  } finally {
    for (const s of sockets) s.destroy();
    await new Promise<void>((resolve) => server.close(() => resolve()));
    await rm(dir, { recursive: true, force: true });
  }
});
